version: '3'

services:
  latest:
    build: .
    image: template/python/jupyter-lab/jl-extensions
    container_name: template_python_jupyter-lab_jl-extensions
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8888:8888
    volumes:
      - ./:/home/
    tty: true
