version: "3.7"

services:
  latest:
    build: .
    image: template/r/jupyter-lab/jl-base
    container_name: template_r_jupyter-lab_jl-base
    ports:
      - 8888:8888
    volumes:
      - ./:/home/
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
