version: "3.7"

services:
  latest:
    build: .
    image: r/base
    container_name : "latest"
    ports:
      - 8787:8787
    environment:
      - USERID=rstudio
      - PASSWORD=pass
    volumes: 
      - ./workspace/:/home/rstudio/workspace/
