version: "3.7"

services:
  latest:
    build: .
    image: template/r/r-studio/rs-base
    container_name : template_r_r-studio_rs-base
    ports:
      - 8787:8787
    environment:
      - USERID=rstudio
      - PASSWORD=pass
    volumes: 
      - ./workspace/:/home/rstudio/workspace/
