# NOW EDITING...

FROM yama07/docker-ubuntu-lxde:ubuntu18.04_ja

#ENV HOME /home
#WORKDIR $HOME/
#COPY .bashrc .vimrc $HOME/

#RUN apt-get update && apt-get upgrade -y \
#  && apt-get install -y \
#    git \
#    vim

